// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaiTwKpp7GBentKvlxaLskFK6W0THEdLc',
    appId: '1:1087771326663:web:ad320596b9380e453a26e2',
    messagingSenderId: '1087771326663',
    projectId: 'workly-be7bb',
    authDomain: 'workly-be7bb.firebaseapp.com',
    storageBucket: 'workly-be7bb.firebasestorage.app',
    measurementId: 'G-JNX2WQ5571',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkikmgfPVFu5fjBxatGQ1QgxYgj7aaKgU',
    appId: '1:1087771326663:android:55b7b174a91910fe3a26e2',
    messagingSenderId: '1087771326663',
    projectId: 'workly-be7bb',
    storageBucket: 'workly-be7bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZ49kgizZ-qmLfW8tH5jJ9bpkYfqZ9LA',
    appId: '1:1087771326663:ios:bab922251ffa50a53a26e2',
    messagingSenderId: '1087771326663',
    projectId: 'workly-be7bb',
    storageBucket: 'workly-be7bb.firebasestorage.app',
    androidClientId: '1087771326663-7ffboetfi9gi14f2do0as44kht0a2pbk.apps.googleusercontent.com',
    iosClientId: '1087771326663-ihno3jj5v0nud425t69m3hbsrc3eed1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZ49kgizZ-qmLfW8tH5jJ9bpkYfqZ9LA',
    appId: '1:1087771326663:ios:bab922251ffa50a53a26e2',
    messagingSenderId: '1087771326663',
    projectId: 'workly-be7bb',
    storageBucket: 'workly-be7bb.firebasestorage.app',
    androidClientId: '1087771326663-7ffboetfi9gi14f2do0as44kht0a2pbk.apps.googleusercontent.com',
    iosClientId: '1087771326663-ihno3jj5v0nud425t69m3hbsrc3eed1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaiTwKpp7GBentKvlxaLskFK6W0THEdLc',
    appId: '1:1087771326663:web:a84e781d15b3463d3a26e2',
    messagingSenderId: '1087771326663',
    projectId: 'workly-be7bb',
    authDomain: 'workly-be7bb.firebaseapp.com',
    storageBucket: 'workly-be7bb.firebasestorage.app',
    measurementId: 'G-PGPXFNDBCE',
  );
}
